### ISSUE TITLE
translation problem after comment module

### ISSUE THREAD

**Issue by blump** [thelia-modules/Comment#5]
When I activate the module for how my product. I lose some translations below
![capture d ecran 2015-04-02 a 22 34 44](https://cloud.githubusercontent.com/assets/10714122/6973078/8079c962-d988-11e4-8751-e982f1f86f28.png)
![capture d ecran 2015-04-02 a 22 33 46](https://cloud.githubusercontent.com/assets/10714122/6973079/80969eb6-d988-11e4-9594-8c35ca6f57c8.png)

**Comment by 40thoughts** [comment]
Running under Thelia Version 2.1.3, I'm having exactly the same problem.
I got the module with git by running : git submodule add <repo> ./local/modules/Comment

Thanks for the work already done
